---
# Array list, with variable name hosts
hosts:
  - 10.0.0.1
  - 10.0.0.2
  - 10.0.0.3
  - 10.0.0.4

# Array list, with variable name samplelist
samplelist:
  - 110.0.0.1
  - 110.0.0.2
  - 110.0.0.3
  - 110.0.0.4

# Variable name complextype
complextype:
  - name: "Chan"
    title: "Manager"
    phone: "99999999"
  - name: "Wong"
    title: "Service"
    phone: "8888888"
  

# simple variable with name myversion
myversion: 9.0.1
