---
# Ansible Playbook to upgrade Cisco IOS 

- name: Upgrade CISCO IOS 
  hosts: 192.168.99.53

  
  vars: 
    upgrade_ios_version: 17.13.01

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is 17.12.04"

    - debug: 
        msg: 
        - "Image is not compliant and will be upgraded"

      when: ansible_net_version != upgrade_ios_version


## Copy software to target device 

    - name: Copy Image // This could take up to 4 minutes
      net_put: 
        src: /IOS/cat9k_iosxe.17.12.04.SPA.bin
        dest: "flash:/cat9k_iosxe.17.12.04.SPA.bin"
      vars: 
        ansible_command_timeout: 600

## Change the Boot Variable to the new image 

    - name: Change Boot Variable to new image 
      ios_config: 
        commands: 
        - "boot system flash:cat9k_iosxe.17.12.04.SPA.bin"
        save_when: always 

## Reload the device 

    - name: Reload the Device 
      cli_command: 
        command: reload
        prompt: 
        - confirm
        answer: 
        - 'y'
         
## Wait for Reachability to the device 

    - name: Wait for device to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 90
      delegate_to: 192.168.99.53

## Check current image 

    - name: Check Image Version      
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"

    - name: ASSERT THAT THE IOS VERSION IS CORRECT
   
      vars: 
        upgrade_ios_version: 17.12.04

      assert:
        that:
        - upgrade_ios_version == ansible_net_version
    - debug: 
        msg: 
        - "Software Upgrade has been completed"


