---
- name: Configure VLANs on Cisco Switches
  hosts: 192.168.99.53
  gather_facts: no
  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_vlans:
        config:
          - name: Vlan_101
            vlan_id: 100
            state: active
            shutdown: false
            remote_span: true
          - name: Vlan_200
            vlan_id: 200
            mtu: 610
            state: active
            shutdown: true
          - name: Vlan_300
            vlan_id: 300
            state: suspended
            shutdown: true
        state: merged
