---
- name: Copy file to switch
  hosts: 192.168.99.53
  tasks:
    - name: Debug
      debug:
        msg: "Copying file to switch"
    - name: Copy file
      copy:
        src: /IOS/cat9k_iosxe.17.12.04.SPA.bin
        dest: /flash:/cat9k_iosxe.17.12.04.SPA.bin

