---
- name: Gather Facts Example
  hosts: all
  tasks:
   - name: Print gathered facts
     debug:
       var: ansible_facts
       
   - name: Check current operating system
     debug:
      msg: "CURRENT IOS IMAGE = {{ ansible_net_image }}"
